### ISSUE TITLE
Suggest reverting encoding/base64 vendoring

### ISSUE THREAD

**Issue by alexzorin** [ericchiang/letsencrypt#10]
In 9be29647abbc951311fa6ec4c0f8f8c99c41970c you vendored encoding/base64, but what this means is that the entire golang repo gets cloned, which takes quite a while to download.

Suggest either just requiring 1.5+ or if not, copying the required code into an internal package.

**Comment by ericchiang** [comment]
When do you have to grab golang/go? Cloning or doing development on this repo doesn't require cloning golang/go. The only time you'd need it would be to add another dependency.

I'd rather have one method for vendoring rather than maintain different strategies for golang/go and square/go-jose .

**Comment by alexzorin** [comment]
The specific repro I have is when attempting to vendor this package using Godep:

```
$ ls
main.go

$ less main.go
package main

import (
        "github.com/ericchiang/letsencrypt"
)

func main() {
        letsencrypt.NewClient("")
}

$ godep save
godep: cannot find package "github.com/golang/go/src/encoding/base64" in any of:
        /usr/local/go/src/github.com/golang/go/src/encoding/base64 (from $GOROOT)
        /home/alex/devel/go/src/github.com/golang/go/src/encoding/base64 (from $GOPATH)
godep: error loading dependencies
```

To be honest, I am not sure if this is instead a problem with Godep (but I don't think so, the real stdlib is at `$GOROOT/src/encoding/base64`). Anyway, I could not vendor this package without reverting the base64 commit.

**Comment by ericchiang** [comment]
Ah. Yeah that's not good. I'll investigate how godep works for packages
within packages and try to figure out a solution.

**Comment by ericchiang** [comment]
Alright, there you go.

Sorry about that one. I realize I haven't actually used godep to import a project with a Godeps directory. Thanks for reporting!
