### ISSUE TITLE
Fails authorizing when using an ECDSA account key of 256 bits

### ISSUE THREAD

**Issue by c4milo** [ericchiang/letsencrypt#18]
The error thrown is the following: 
square/go-jose: expected 384 bit key, got 256 bits instead

**Comment by ericchiang** [comment]
Why is your ECDSA key so small? I don't know if acme allows keys to be that few bits.

**Comment by c4milo** [comment]
The size is perfectly fine for a ECDSA signing algorithm.

**Comment by c4milo** [comment]
Unless, LetsEncrypt is strictly following NIST recommendations for key lenghts: https://www.keylength.com/en/6/

**Comment by ericchiang** [comment]
This would be the bug

https://github.com/ericchiang/letsencrypt/blob/a095679ba87c40b35e2fb94c62651b79594bdd58/acme.go#L429

I think that value should be jose.ES256

**Comment by c4milo** [comment]
Right, they allow 256bits for ECDSA: https://github.com/letsencrypt/boulder/blob/master/core/good_key.go#L171

**Comment by ericchiang** [comment]
Awesome. Feel free to open an PR for this (or I can fix it later).

**Comment by c4milo** [comment]
I'll send you a PR shortly.

**Comment by c4milo** [comment]
PR sent: https://github.com/ericchiang/letsencrypt/pull/19
