### ISSUE TITLE
Godeps path

### ISSUE THREAD

**Issue by cristiangraz** [ericchiang/letsencrypt#3]
In this file: https://github.com/ericchiang/letsencrypt/blob/master/Godeps/Godeps.json#L2

Shouldn't the Godeps ImportPath be:

`github.com/ericchiang/letsencrypt` rather than `github.com/ericchiang/acme`?

When I run go get, all of the import paths are referencing the non-existent `"github.com/ericchiang/acme/Godeps/_workspace/src/github.com/square/go-jose/cipher"` (for example) path. I had to manually change to `"github.com/ericchiang/letsencrypt/Godeps/_workspace/src/github.com/square/go-jose/cipher"` to get things working (for all Godeps imports).

**Comment by ericchiang** [comment]
thanks!
