### ISSUE TITLE
Please rename project as it violates ISRG trademark

### ISSUE THREAD

**Issue by bdaehlie** [ericchiang/letsencrypt#31]
We (ISRG / Let's Encrypt) do not allow clients to use our service's name in their client name. We recommend you use the term "ACME" instead, in reference to the protocol. This is better because there are no trademark issues and the protocol is not specific to our CA so your client should work with other ACME-enabled CAs in the future.

I know this can be a pain but we have to insist that the name change. Thanks for understanding.

**Comment by ericchiang** [comment]
Done. I've been looking to deprecate in favor of https://godoc.org/golang.org/x/crypto/acme/autocert
