### ISSUE TITLE
Authorization.Combinations appears to be broken

### ISSUE THREAD

**Issue by alexzorin** [ericchiang/letsencrypt#7]
We are getting 0 (zero) supported challenges returned from `Authorization.Challenges` depending on what order the challenges are listed in the response from Boulder (using the Let's Encrypt "staging" server).

We are calling:

```
chals := auth.Combinations(letsencrypt.ChallengeHTTP)
```

and getting an empty slice in return.

Here is a `%#v` dump of the `Authorization` struct from Boulder, where the library successfully finds the HTTP challenge:

> 2015/11/24 13:45:25 Challenges: letsencrypt.Authorization{Identifier:struct { Type string "json:\"type\""; Value string "json:\"value\"" }{Type:"dns", Value:"MYDOMAIN.TLD"}, Status:"pending", Expires:time.Time{sec:63584534725, nsec:669278071, loc:(_time.Location)(0xa40800)}, Challenges:[]letsencrypt.Challenge{letsencrypt.Challenge{ID:0, Type:"tls-sni-01", URI:"https://acme-staging.api.letsencrypt.org/acme/challenge/Phcunxr4uNcjMr_uwXi_UNy-Aj-TThKDY4_qQYyEiIc/736693", Status:"pending", Validated:time.Time{sec:0, nsec:0, loc:(_time.Location)(nil)}, Error:(_letsencrypt.Error)(nil), Token:"_CYm7ZGvn-B4HT-09wcfjKM_RDrZsjOk0EX9W9yfvDU", KeyAuthorization:"", N:0, Certs:[]string(nil), AccountKey:(_jose.JsonWebKey)(nil), Authorization:(_letsencrypt.JWSValidation)(nil)}, letsencrypt.Challenge{ID:0, Type:"http-01", URI:"https://acme-staging.api.letsencrypt.org/acme/challenge/Phcunxr4uNcjMr_uwXi_UNy-Aj-TThKDY4_qQYyEiIc/736694", Status:"pending", Validated:time.Time{sec:0, nsec:0, loc:(_time.Location)(nil)}, Error:(_letsencrypt.Error)(nil), Token:"bvLXXINiw2b-fYU4NIA3aqG5d-CkUyhCzvs74dnlO2U", KeyAuthorization:"", N:0, Certs:[]string(nil), AccountKey:(_jose.JsonWebKey)(nil), Authorization:(*letsencrypt.JWSValidation)(nil)}}, Combs:[][]int{[]int{0}, []int{1}}}

And here is one that fails to find the `http-01` type, even though it is in there.

> 2015/11/24 13:43:57 Challenges: letsencrypt.Authorization{Identifier:struct { Type string "json:\"type\""; Value string "json:\"value\"" }{Type:"dns", Value:"MYDOMAIN.TLD"}, Status:"pending", Expires:time.Time{sec:63584534637, nsec:599494120, loc:(_time.Location)(0xa40800)}, Challenges:[]letsencrypt.Challenge{letsencrypt.Challenge{ID:0, Type:"http-01", URI:"https://acme-staging.api.letsencrypt.org/acme/challenge/tcxd_fNpMb4ux7JW_3VBLsJltGaNefhi0fv_sX0i8N0/736689", Status:"pending", Validated:time.Time{sec:0, nsec:0, loc:(_time.Location)(nil)}, Error:(_letsencrypt.Error)(nil), Token:"EMX9y_ge-HBej8zzt2HttUhX8_QeOI_HoUADJlNSXn8", KeyAuthorization:"", N:0, Certs:[]string(nil), AccountKey:(_jose.JsonWebKey)(nil), Authorization:(_letsencrypt.JWSValidation)(nil)}, letsencrypt.Challenge{ID:0, Type:"tls-sni-01", URI:"https://acme-staging.api.letsencrypt.org/acme/challenge/tcxd_fNpMb4ux7JW_3VBLsJltGaNefhi0fv_sX0i8N0/736690", Status:"pending", Validated:time.Time{sec:0, nsec:0, loc:(_time.Location)(nil)}, Error:(_letsencrypt.Error)(nil), Token:"xp9XshTGRC0wRb8jGqp2gukphD9Purh5h9Wpk84jP9Y", KeyAuthorization:"", N:0, Certs:[]string(nil), AccountKey:(_jose.JsonWebKey)(nil), Authorization:(*letsencrypt.JWSValidation)(nil)}}, Combs:[][]int{[]int{1}, []int{0}}}

**Comment by cainjonm** [comment]
https://github.com/ericchiang/letsencrypt/blob/master/objects.go#L70 the bound checking `idx > 0` should be changed to `idx >= 0`

**Comment by alexzorin** [comment]
Thanks @cainjonm , that appears to have fixed it - now it finds the challenge in both cases.
